added checkbox component doc
Nature-UI/nature-ui-docs pull request #12
Opened 2022-11-16 05:35 UTC by RahmanC

2022-11-17 06:26 UTC, DNature requested changes
Please always compare your changes with the storybook docs.

2022-11-17 06:26 UTC, DNature commented on content/docs/components/checkbox/usage.mdx
> +The `Checkbox` component is used in forms when a user needs to select multiple
This looks like a duplicate of the description. I'd suggest you override the description with this sentence

2022-11-17 06:26 UTC, DNature commented on content/docs/components/checkbox/usage.mdx
> +  <Checkbox color='purple-500' defaultIsChecked>
Color prop is deprecated. please see the [storybook documentation](https://github.com/Nature-UI/nature-ui/blob/6ec4a1de81fd3963c02aafefdc9f476d1678f071/packages/checkbox/stories/checkbox.stories.tsx) for more details. 

we now use: `className="bg-purple-500"`

2022-11-19 19:56 UTC, RahmanC commented on content/docs/components/checkbox/usage.mdx
> +The `Checkbox` component is used in forms when a user needs to select multiple
This has been resolved

2022-11-19 19:56 UTC, RahmanC commented on content/docs/components/checkbox/usage.mdx
> +  <Checkbox color='purple-500' defaultIsChecked>
this issue has been updated

2022-12-03 13:47 UTC, DNature commented
Hi @RahmanC , please click the "Resolve conversation" button once you've resolved any comments. Also ping me on discord so I can review your PR

2022-12-03 13:50 UTC, DNature requested changes

2022-12-03 13:50 UTC, DNature commented on content/docs/components/checkbox/usage.mdx
> +  <Checkbox color='bg-purple-500' defaultIsChecked>
Replace `color` with `className`

2022-12-03 13:50 UTC, DNature commented on content/docs/components/checkbox/usage.mdx
> +  <Checkbox color='bg-green-500' defaultIsChecked>
Same here

2022-12-03 13:50 UTC, DNature commented on content/docs/components/checkbox/usage.mdx
> +  <Checkbox size='lg' color='bg-orange-500' defaultIsChecked>
Same here. `color` should be `className`

2022-12-12 16:18 UTC, DNature commented
@RahmanC This PR has been opened for too long. I'll close it by the end of this week so that someone else can pickup the ticket.

2022-12-17 07:49 UTC, DNature approved these changes

2022-12-23 16:09 UTC, merged

2023-03-31 18:26 UTC, DNature commented
<img width="827" alt="Screenshot 2023-03-31 at 20 25 38" src="https://user-images.githubusercontent.com/49137104/229200408-59fceebb-f5f7-45e7-9385-5d0a22589d6b.png">