#73 73-popover-component
Nature-UI/nature-ui-docs pull request #74
Opened 2022-12-12 09:09 UTC by success-h

added popover component to docs

2022-12-12 16:14 UTC, DNature commented on content/docs/components/popover/usage.mdx
> +clickable trigger element.
This is a duplicate description because we already have `description` in the front-matter metadata.

2022-12-13 19:51 UTC, success-h commented on content/docs/components/popover/usage.mdx
> +clickable trigger element.
Thanks so much for the corrections. I just made the corrections

2022-12-13 20:22 UTC, success-h commented on content/docs/components/popover/usage.mdx
> +clickable trigger element.
please review again

2022-12-15 06:59 UTC, DNature requested changes

2022-12-15 06:59 UTC, DNature commented on content/docs/components/popover/usage.mdx
> +and composes the `Popper` component.
This is a continuation of the description. please move it there.

2022-12-15 07:00 UTC, DNature commented on content/docs/components/popover/usage.mdx
> +and composes the `Popper` component.
9 - 14

2022-12-15 14:20 UTC, DNature approved these changes
LGTM

2022-12-15 14:20 UTC, merged