#76 created NumberInput component docs - NumberInput
Nature-UI/nature-ui-docs pull request #82
Opened 2022-12-18 23:45 UTC by success-h

2022-12-22 06:56 UTC, DNature requested changes

2022-12-22 06:56 UTC, DNature commented on content/docs/components/number-input/usage.mdx
> +import React from "react";
Remove `React` import.

2022-12-22 06:59 UTC, success-h commented on content/docs/components/number-input/usage.mdx
> +import React from "react";
Done

2022-12-22 09:23 UTC, DNature approved these changes

2022-12-23 15:55 UTC, DNature approved these changes

2022-12-23 15:56 UTC, merged